package kz.hackalem.wamigos.error;

public enum ErrorCode {
    INVALID_REQUEST,
    MEETING_NOT_AVAILABLE,
    FILE_TOO_LARGE,
    UNSUPPORTED_MEDIA_TYPE,
    MEDIA_NOT_DECODABLE,
    NO_AUDIO_TRACK,
    DURATION_LIMIT_EXCEEDED,
    QUEUE_FULL,
    PROCESSING_INTERRUPTED,
    PROCESSING_TIMEOUT,
    AI_PROCESSING_FAILED,
    EXPORT_NOT_READY,
    EXPORT_FAILED,
    STORAGE_ERROR,
    INTERNAL_ERROR
}
